#!/usr/bin/env python3
#
# Date: 2026-01-25
# Version: 1.0.0
# Purpose: HTTP helpers for Canvas API requests, including pagination.
# Usage: Imported by other modules.
# Input: Canvas base URL and token; endpoint URL.
# Output: Decoded JSON objects (Python dict/list).
# Chat name: Canvas SpeedGrader Archive
# GPT Model: GPT-5.2 Thinking
# Attribution: Generated by Michael Gilchrist in collaboration with ChatGPT.

import json
import urllib.request


def http_get_json(url, token):
    req = urllib.request.Request(url)
    req.add_header("Authorization", f"Bearer {token}")
    req.add_header("Accept", "application/json")
    with urllib.request.urlopen(req) as resp:
        body = resp.read().decode("utf-8")
        return json.loads(body), resp.headers


def parse_next_link(headers):
    link = headers.get("Link")
    if not link:
        return None
    parts = [p.strip() for p in link.split(",")]
    for p in parts:
        if 'rel="next"' in p:
            lt = p.find("<")
            gt = p.find(">")
            if lt >= 0 and gt > lt:
                return p[lt + 1:gt]
    return None


def paginated_get_all(url, token, verbose=False):
    out = []
    cur = url
    while cur:
        if verbose:
            print(f"[GET] {cur}")
        data, headers = http_get_json(cur, token)
        if isinstance(data, list):
            out.extend(data)
        else:
            out.append(data)
        cur = parse_next_link(headers)
    return out
