#!/usr/bin/env python3
#
# Date: 2026-01-25
# Version: 1.0.1
# Purpose: Minimal Canvas API endpoint wrappers used for Classic Quiz response extraction.
# Usage: Imported by api_to_json.py.
# Input: Canvas base URL, token, course_id, quiz_id, submission_id.
# Output: Raw API JSON payloads.
# Chat name: Canvas SpeedGrader Archive
# GPT Model: GPT-5.2 Thinking
# Attribution: Generated by Michael Gilchrist in collaboration with ChatGPT.

from canvas_http import paginated_get_all, paginated_get_all_list_key


def get_quiz_submissions(base_url, token, course_id, quiz_id, verbose=False):
    url = f"{base_url}/api/v1/courses/{course_id}/quizzes/{quiz_id}/submissions?include[]=quiz&per_page=100"
    # Canvas returns {"quiz_submissions":[...]} for this endpoint.
    return paginated_get_all_list_key(url, token, "quiz_submissions", verbose=verbose)


def get_quiz_questions(base_url, token, course_id, quiz_id, verbose=False):
    url = f"{base_url}/api/v1/courses/{course_id}/quizzes/{quiz_id}/questions"
    return paginated_get_all(url, token, verbose=verbose)


def get_submission_questions(base_url, token, submission_id, verbose=False):
    url = f"{base_url}/api/v1/quiz_submissions/{submission_id}/questions?include[]=quiz_question&per_page=100"
    # This endpoint typically returns a list; some instances may wrap it.
    return paginated_get_all_list_key(url, token, "quiz_submission_questions", verbose=verbose)
