#!/usr/bin/env python3
#
# Date: 2026-01-25
# Version: 1.0.0
# Purpose: Render canonical per-submission JSON files to readable HTML files.
# Usage: json_to_html.py JSON_DIR [--outdir DIR] [--dry-run] [--verbose]
# Input: Canonical JSON files from ./output/JSON (or any folder).
# Output: One HTML file per submission in ./output/HTML by default.
# Chat name: Canvas SpeedGrader Archive
# GPT Model: GPT-5.2 Thinking
# Attribution: Generated by Michael Gilchrist in collaboration with ChatGPT.

import argparse
import os

from io_utils import list_json_files, read_json
from render_html import render_submission_html


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("json_dir")
    ap.add_argument("--outdir", default=os.path.join("output", "HTML"))
    ap.add_argument("--dry-run", action="store_true")
    ap.add_argument("--verbose", action="store_true")
    args = ap.parse_args()

    paths = list_json_files(args.json_dir)
    if args.verbose:
        print(f"[INFO] JSON files: {len(paths)}")

    if args.dry_run:
        print(f"[DRY RUN] Would write HTML files to: {args.outdir}")
        return

    os.makedirs(args.outdir, exist_ok=True)
    for p in paths:
        doc = read_json(p)
        sid = (doc.get("submission") or {}).get("submission_id")
        if sid is None:
            continue
        html_text = render_submission_html(doc)
        outpath = os.path.join(args.outdir, f"submission_{int(sid)}.html")
        with open(outpath, "w", encoding="utf-8") as f:
            f.write(html_text)

    if args.verbose:
        print("[INFO] Done.")


if __name__ == "__main__":
    main()
