#!/usr/bin/env python3
#
# Date: 2026-01-25
# Version: 1.0.0
# Purpose: Convenience wrapper: canonical JSON -> HTML and SQLite in one command.
# Usage: json_to_all.py JSON_DIR OUTDB [--html-outdir DIR] [--dry-run] [--verbose]
# Input: Canonical JSON folder and output database path.
# Output: HTML files and SQLite database.
# Chat name: Canvas SpeedGrader Archive
# GPT Model: GPT-5.2 Thinking
# Attribution: Generated by Michael Gilchrist in collaboration with ChatGPT.

import argparse
import os

from io_utils import list_json_files, read_json
from render_html import render_submission_html
from sqlite_writer import init_db, write_doc


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("json_dir")
    ap.add_argument("outdb")
    ap.add_argument("--html-outdir", default=os.path.join("output", "HTML"))
    ap.add_argument("--dry-run", action="store_true")
    ap.add_argument("--verbose", action="store_true")
    args = ap.parse_args()

    paths = list_json_files(args.json_dir)
    if args.verbose:
        print(f"[INFO] JSON files: {len(paths)}")

    if args.dry_run:
        print(f"[DRY RUN] Would write HTML files to: {args.html_outdir}")
        print(f"[DRY RUN] Would write SQLite DB to: {args.outdb}")
        return

    os.makedirs(args.html_outdir, exist_ok=True)
    os.makedirs(os.path.dirname(args.outdb) or ".", exist_ok=True)

    conn = init_db(args.outdb)
    for p in paths:
        doc = read_json(p)
        sid = (doc.get("submission") or {}).get("submission_id")

        write_doc(conn, doc)

        if sid is not None:
            html_text = render_submission_html(doc)
            outpath = os.path.join(args.html_outdir, f"submission_{int(sid)}.html")
            with open(outpath, "w", encoding="utf-8") as f:
                f.write(html_text)

    conn.close()
    if args.verbose:
        print("[INFO] Done.")


if __name__ == "__main__":
    main()
