#!/usr/bin/env python3
#
# Date: 2026-01-25
# Version: 1.0.0
# Purpose: Load canonical per-submission JSON files into a SQLite database.
# Usage: json_to_sqlite.py JSON_DIR OUTDB [--dry-run] [--verbose]
# Input: Canonical JSON files folder and output database path.
# Output: SQLite database written to OUTDB.
# Chat name: Canvas SpeedGrader Archive
# GPT Model: GPT-5.2 Thinking
# Attribution: Generated by Michael Gilchrist in collaboration with ChatGPT.

import argparse
import os

from io_utils import list_json_files, read_json
from sqlite_writer import init_db, write_doc


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("json_dir")
    ap.add_argument("outdb")
    ap.add_argument("--dry-run", action="store_true")
    ap.add_argument("--verbose", action="store_true")
    args = ap.parse_args()

    paths = list_json_files(args.json_dir)
    if args.verbose:
        print(f"[INFO] JSON files: {len(paths)}")

    if args.dry_run:
        print(f"[DRY RUN] Would write SQLite DB to: {args.outdb}")
        return

    os.makedirs(os.path.dirname(args.outdb) or ".", exist_ok=True)
    conn = init_db(args.outdb)
    for p in paths:
        doc = read_json(p)
        write_doc(conn, doc)
    conn.close()

    if args.verbose:
        print("[INFO] Done.")


if __name__ == "__main__":
    main()
