#!/usr/bin/env python3
#
# Date: 2026-01-25
# Version: 1.0.0
# Purpose: Convert mock Canvas API JSON payloads (from SpeedGrader HTML converter) into canonical per-submission JSON files.
# Usage: mock_to_json.py MOCK_DIR [--outdir DIR] [--dry-run] [--verbose]
# Input: mock_quiz_submissions.json, mock_quiz_questions.json, mock_quiz_submission_<id>_questions.json
# Output: Canonical per-submission JSON files in ./output/JSON by default.
# Chat name: Canvas SpeedGrader Archive
# GPT Model: GPT-5.2 Thinking
# Attribution: Generated by Michael Gilchrist in collaboration with ChatGPT.

import argparse
import os

from io_utils import read_json, write_json
from model import canonicalize_submission


def find_submission_questions_file(mock_dir, submission_id):
    return os.path.join(mock_dir, f"mock_quiz_submission_{submission_id}_questions.json")


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("mock_dir")
    ap.add_argument("--outdir", default=os.path.join("output", "JSON"))
    ap.add_argument("--dry-run", action="store_true")
    ap.add_argument("--verbose", action="store_true")
    args = ap.parse_args()

    subs = read_json(os.path.join(args.mock_dir, "mock_quiz_submissions.json"))
    qqs = read_json(os.path.join(args.mock_dir, "mock_quiz_questions.json"))

    if args.verbose:
        print(f"[INFO] Mock submissions: {len(subs)}")

    if args.dry_run:
        print(f"[DRY RUN] Would write JSON files to: {args.outdir}")
        return

    for sub in subs:
        sid = sub.get("id")
        if sid is None:
            continue
        sq_path = find_submission_questions_file(args.mock_dir, int(sid))
        sqs = read_json(sq_path)
        doc = canonicalize_submission(sub, sqs, qqs)
        doc["source"]["mode"] = "mock"
        doc["source"]["notes"] = "Canonicalized from mock payloads (SpeedGrader HTML export)."
        outpath = os.path.join(args.outdir, f"submission_{int(sid)}.json")
        write_json(outpath, doc)

    if args.verbose:
        print("[INFO] Done.")


if __name__ == "__main__":
    main()
