#!/usr/bin/env python3
#
# Date: 2026-01-25
# Version: 1.0.0
# Purpose: Canonical data model construction: raw API payloads -> canonical per-submission JSON dict.
# Usage: Imported by api_to_json.py and mock_to_json.py.
# Input: Raw Canvas API JSON payloads.
# Output: Canonical per-submission dict with submission header and question records.
# Chat name: Canvas SpeedGrader Archive
# GPT Model: GPT-5.2 Thinking
# Attribution: Generated by Michael Gilchrist in collaboration with ChatGPT.

import datetime as dt


def now_utc_iso():
    return dt.datetime.utcnow().replace(microsecond=0).isoformat() + "Z"


def build_question_lookup(quiz_questions):
    out = {}
    for qq in quiz_questions:
        qid = qq.get("id")
        if qid is None:
            continue
        out[int(qid)] = {
            "question_id": int(qid),
            "question_position": qq.get("position"),
            "question_type": qq.get("question_type"),
            "question_prompt_html": qq.get("question_text"),
            "points_possible": qq.get("points_possible"),
            "question_key_html": qq.get("neutral_comments"),
        }
    return out


def canonicalize_submission(sub, submission_questions, quiz_questions):
    submission_id = sub.get("id")
    quiz_id = sub.get("quiz_id")
    user_id = sub.get("user_id")

    if submission_id is None or quiz_id is None:
        raise ValueError("submission object missing id or quiz_id")

    header = {
        "submission_id": int(submission_id),
        "student_id": int(user_id) if user_id is not None else None,
        "quiz_id": int(quiz_id),
        "quiz_name": (sub.get("quiz") or {}).get("title"),
        "time_start": sub.get("started_at"),
        "time_end": sub.get("finished_at"),
        "time_total": sub.get("time_spent"),
        "points_total": sub.get("score"),
    }

    q_lookup = build_question_lookup(quiz_questions)

    questions = []
    for sq in submission_questions:
        qqref = sq.get("quiz_question") or {}
        qid = qqref.get("id")
        if qid is None:
            continue
        qid = int(qid)

        meta = q_lookup.get(qid, {})

        resp_obj = sq.get("answer")

        # Best-effort "view" string (often the dict["value"] for text responses)
        resp_html = None
        if isinstance(resp_obj, dict) and "value" in resp_obj:
            resp_html = resp_obj.get("value")
        else:
            resp_html = resp_obj

        questions.append({
            "submission_id": header["submission_id"],
            "student_id": header["student_id"],
            "quiz_id": header["quiz_id"],

            "question_id": qid,
            "question_position": meta.get("question_position"),
            "question_type": meta.get("question_type"),

            "points_possible": meta.get("points_possible"),
            "earned_points": sq.get("earned_points"),

            "question_prompt_html": meta.get("question_prompt_html"),
            "question_key_html": meta.get("question_key_html"),

            "question_response_obj": resp_obj,
            "question_response_html": resp_html,
        })

    return {
        "submission": header,
        "questions": questions,
        "generated_utc": now_utc_iso(),
        "source": {
            "mode": None,
            "notes": None,
        },
    }
