#!/usr/bin/env python3
#
# Date: 2026-01-25
# Version: 1.0.0
# Purpose: Render canonical per-submission JSON dict to a simple readable HTML file.
# Usage: Imported by json_to_html.py (and json_to_all.py).
# Input: Canonical per-submission dict.
# Output: HTML string.
# Chat name: Canvas SpeedGrader Archive
# GPT Model: GPT-5.2 Thinking
# Attribution: Generated by Michael Gilchrist in collaboration with ChatGPT.

import html


def normalize_single_newlines(s):
    # Replace single newlines with spaces, keep multiple newlines.
    if s is None:
        return None
    s = str(s).replace("\r\n", "\n").replace("\r", "\n")
    marker = "__KEEP_MULTILINE_BREAK__"
    while "\n\n" in s:
        s = s.replace("\n\n", marker)
    s = s.replace("\n", " ")
    while marker in s:
        s = s.replace(marker, "\n\n")
    return s


def esc_text(x):
    x2 = normalize_single_newlines(x)
    return html.escape("" if x2 is None else str(x2))


def render_submission_html(doc):
    sub = doc.get("submission") or {}
    questions = doc.get("questions") or []

    blocks = []
    for q in questions:
        resp = q.get("question_response_html")
        resp_disp = normalize_single_newlines(resp)
        blocks.append(f'''
    <article class="question"
             submission_id="{esc_text(q.get("submission_id"))}"
             student_id="{esc_text(q.get("student_id"))}"
             quiz_id="{esc_text(q.get("quiz_id"))}"
             question_id="{esc_text(q.get("question_id"))}"
             question_position="{esc_text(q.get("question_position"))}"
             question_type="{esc_text(q.get("question_type"))}">
      <h3>Question {esc_text(q.get("question_position"))}</h3>

      <dl>
        <dt>submission_id</dt><dd>{esc_text(q.get("submission_id"))}</dd>
        <dt>student_id</dt><dd>{esc_text(q.get("student_id"))}</dd>
        <dt>quiz_id</dt><dd>{esc_text(q.get("quiz_id"))}</dd>
        <dt>question_id</dt><dd>{esc_text(q.get("question_id"))}</dd>

        <dt>points_possible</dt><dd>{esc_text(q.get("points_possible"))}</dd>
        <dt>earned_points</dt><dd>{esc_text(q.get("earned_points"))}</dd>
      </dl>

      <div class="field-label">question_prompt</div>
      <div class="question_prompt">{esc_text(q.get("question_prompt_html"))}</div>

      <div class="field-label">question_response</div>
      <div class="question_response">{html.escape("" if resp_disp is None else str(resp_disp))}</div>

      <div class="field-label">question_key</div>
      <div class="question_key">{esc_text(q.get("question_key_html"))}</div>
    </article>
''')

    return f'''<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <title>Canvas Quiz Archive - submission_id={esc_text(sub.get("submission_id"))}</title>
  <style>
    body {{ font-family: sans-serif; margin: 1.25rem; }}
    h1, h2, h3 {{ margin: 0.5rem 0; }}
    .muted {{ color: #555; }}
    .submission, .question {{ border: 1px solid #ccc; padding: 0.75rem; border-radius: 6px; margin: 0.75rem 0; }}
    dl {{ display: grid; grid-template-columns: 12rem 1fr; gap: 0.25rem 0.75rem; margin: 0; }}
    dt {{ font-weight: bold; }}
    dd {{ margin: 0; }}
    .field-label {{ font-weight: bold; margin-top: 0.5rem; }}
    .question_response {{ white-space: normal; }}
  </style>
</head>
<body>
  <h1>Canvas Quiz Archive</h1>
  <p class="muted">Human-readable view. Canonical data is JSON (separately saved) and can be loaded into SQLite.</p>

  <section class="submission"
           submission_id="{esc_text(sub.get("submission_id"))}"
           student_id="{esc_text(sub.get("student_id"))}"
           quiz_id="{esc_text(sub.get("quiz_id"))}">
    <h2>Submission</h2>
    <dl>
      <dt>submission_id</dt><dd>{esc_text(sub.get("submission_id"))}</dd>
      <dt>student_id</dt><dd>{esc_text(sub.get("student_id"))}</dd>
      <dt>quiz_id</dt><dd>{esc_text(sub.get("quiz_id"))}</dd>
      <dt>quiz_name</dt><dd>{esc_text(sub.get("quiz_name"))}</dd>

      <dt>time_start</dt><dd>{esc_text(sub.get("time_start"))}</dd>
      <dt>time_end</dt><dd>{esc_text(sub.get("time_end"))}</dd>
      <dt>time_total</dt><dd>{esc_text(sub.get("time_total"))}</dd>

      <dt>points_total</dt><dd>{esc_text(sub.get("points_total"))}</dd>
    </dl>
  </section>

  <section class="questions">
    <h2>Questions</h2>
{''.join(blocks)}
  </section>
</body>
</html>
'''
