#!/usr/bin/env python3
#
# Date: 2026-02-19
# Version: 1.0.3
# Purpose: Fetch Classic Quiz data via Canvas API and write canonical per-submission JSON files.
# Usage: api_to_json.py COURSE_ID QUIZ_ID --base-url URL --token-file FILE [--outdir DIR] [--dry-run] [--verbose]
# Input: Canvas API token + course_id + quiz_id.
# Output: One canonical JSON file per submission in ./output/JSON by default.
# Chat name: Canvas SpeedGrader Archive
# GPT Model: GPT-5.2 Thinking
# Attribution: Generated by Michael Gilchrist in collaboration with ChatGPT.

import argparse
import os
import urllib.error

from canvas_api import get_quiz_questions, get_quiz_submissions, get_submission_questions
from io_utils import load_profile, read_token, write_json
from model import canonicalize_submission


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("course_id", type=int)
    ap.add_argument("quiz_id", type=int)

    ap.add_argument("--base-url", default=None,
                    help="Canvas instance URL (or set base_url in "
                         "~/.canvas.api.conf)")
    ap.add_argument("--token", default=None)
    ap.add_argument("--token-file", default=None,
                    help="Path to token file (or set token_file in "
                         "~/.canvas.api.conf)")

    ap.add_argument("--outdir", default=os.path.join("output", "JSON"))
    ap.add_argument("--dry-run", action="store_true")
    ap.add_argument("--verbose", action="store_true")

    args = ap.parse_args()

    profile = load_profile()
    if not args.base_url:
        args.base_url = profile.get("base_url")
    if not args.base_url:
        ap.error("--base-url is required (or set base_url in "
                 "~/.canvas.api.conf)")
    token = read_token(args.token, args.token_file, profile)
    base_url = args.base_url.rstrip("/")

    if args.verbose:
        print("[INFO] Fetching quiz questions...")
    try:
        quiz_questions = get_quiz_questions(base_url, token, args.course_id, args.quiz_id, verbose=args.verbose)
    except urllib.error.HTTPError as e:
        # UTK returns 403 for /quizzes/:id/questions even for instructors.
        if e.code == 403:
            quiz_questions = []
            if args.verbose:
                print("[WARN] 403 on quiz questions endpoint; continuing without question_prompt_html/question_key_html.")
        else:
            raise

    if args.verbose:
        print("[INFO] Fetching quiz submissions...")
    submissions = get_quiz_submissions(base_url, token, args.course_id, args.quiz_id, verbose=args.verbose)

    if args.verbose:
        print(f"[INFO] Submissions: {len(submissions)}")

    if args.dry_run:
        print(f"[DRY RUN] Would write JSON files to: {args.outdir}")
        return

    for sub in submissions:
        sid = sub.get("id")
        if sid is None:
            continue
        if args.verbose:
            print(f"[INFO] Fetching submission questions for submission_id={sid}")
        sub_questions = get_submission_questions(base_url, token, int(sid), verbose=args.verbose)
        doc = canonicalize_submission(sub, sub_questions, quiz_questions)
        doc["source"]["mode"] = "api"
        doc["source"]["notes"] = "Canonicalized from Canvas API payloads."
        outpath = os.path.join(args.outdir, f"submission_{int(sid)}.json")
        write_json(outpath, doc)

    if args.verbose:
        print("[INFO] Done.")


if __name__ == "__main__":
    main()
