#!/usr/bin/env python3
# ============================================================================
# Script:       list_courses.py
# Version:      1.0.0
# Date:         2026-02-20
# Purpose:      List Canvas courses for the authenticated user with ID,
#               term, student count, state, and title.  Filter by year,
#               semester, or active status.
#
# Usage:        list_courses.py --base-url URL
#                   [--token TOKEN | --token-file FILE]
#                   [-y YEAR] [-s SEMESTER] [--active-only]
#                   [--dry-run] [--verbose] [--help]
#
# Input:        Canvas API token
# Output:       Tabular course listing to stdout
#
# Options:
#   --base-url URL          Canvas instance URL (required)
#   --token TOKEN           Inline API token
#   --token-file FILE       Path to file containing API token
#   -y, --year YEAR         Filter by year in term name (e.g. 2026)
#   -s, --semester NAME     Filter by semester in term name (e.g. Spring)
#   --active-only           Only show courses with state "available"
#   -n, --dry-run           Show the API URL that would be fetched
#   -v, --verbose           Show detailed output
#   -h, --help              Show this help message
#
# Session:      Canvas API Assignments
# AI Model:     Claude Opus 4.6
# Attribution:  Generated by Michael Gilchrist in collaboration with
#               ClaudeAI Opus 4.6
# ============================================================================

import argparse

from canvas_api import get_courses
from io_utils import load_profile, read_token


def main():
    ap = argparse.ArgumentParser(
        description="List Canvas courses for the authenticated user.")

    ap.add_argument("--base-url", default=None,
                    help="Canvas instance URL (or set base_url in "
                         "~/.canvas.api.conf)")
    ap.add_argument("--token", default=None,
                    help="Canvas API token (inline)")
    ap.add_argument("--token-file", default=None,
                    help="Path to token file (or set token_file in "
                         "~/.canvas.api.conf)")

    ap.add_argument("-y", "--year", default=None,
                    help="Filter by year in term name (e.g. 2026)")
    ap.add_argument("-s", "--semester", default=None,
                    help="Filter by semester in term name "
                         "(e.g. Spring, Fall, Summer)")
    ap.add_argument("--active-only", action="store_true",
                    help="Only show courses with state 'available'")

    ap.add_argument("-n", "--dry-run", action="store_true",
                    help="Show the API URL that would be fetched "
                         "without making requests")
    ap.add_argument("-v", "--verbose", action="store_true",
                    help="Show detailed output")

    args = ap.parse_args()

    profile = load_profile()
    if not args.base_url:
        args.base_url = profile.get("base_url")
    if not args.base_url:
        ap.error("--base-url is required (or set base_url in "
                 "~/.canvas.api.conf)")
    token = read_token(args.token, args.token_file, profile)
    base_url = args.base_url.rstrip("/")

    # Dry-run: show what would be fetched and exit
    if args.dry_run:
        url = (f"{base_url}/api/v1/courses"
               f"?per_page=100&include[]=term&include[]=total_students")
        print(f"[DRY RUN] Would fetch: {url}")
        filters = []
        if args.year:
            filters.append(f"year={args.year}")
        if args.semester:
            filters.append(f"semester={args.semester}")
        if args.active_only:
            filters.append("active-only")
        if filters:
            print(f"[DRY RUN] Client-side filters: {', '.join(filters)}")
        return

    if args.verbose:
        print("[INFO] Fetching courses...")

    courses = get_courses(base_url, token, verbose=args.verbose)

    # Apply filters
    if args.active_only:
        courses = [c for c in courses
                   if c.get("workflow_state") == "available"]

    if args.year or args.semester:
        filtered = []
        for c in courses:
            term_name = c.get("term", {}).get("name", "")
            if args.year and args.year not in term_name:
                continue
            if args.semester:
                if args.semester.lower() not in term_name.lower():
                    continue
            filtered.append(c)
        courses = filtered

    # Sort by term name then course name
    courses.sort(key=lambda c: (
        c.get("term", {}).get("name", ""),
        c.get("name", "")))

    if not courses:
        print("No courses matched filters.")
        return

    # Print table
    print(f"{'ID':>8}  {'Students':>8}  {'State':<10}  "
          f"{'Term':<20}  Name")
    print(f"{'---':>8}  {'---':>8}  {'---':<10}  "
          f"{'---':<20}  ---")

    for c in courses:
        cid = c.get("id", "")
        name = c.get("name", "(untitled)")
        state = c.get("workflow_state", "")
        term_name = c.get("term", {}).get("name", "-")
        if len(term_name) > 20:
            term_name = term_name[:19] + "."
        students = c.get("total_students")
        stu_str = str(students) if students is not None else "-"

        print(f"{cid:>8}  {stu_str:>8}  {state:<10}  "
              f"{term_name:<20}  {name}")

    print(f"\nTotal: {len(courses)} courses")


if __name__ == "__main__":
    main()
