#!/usr/bin/env python3
#
# Date: 2026-02-19
# Version: 1.3.0
# Purpose: Canvas API endpoint wrappers for Classic Quiz archival and
#          QTI content migration imports.
# Usage: Imported by CLI scripts.
# Input: Canvas base URL, token, course_id, and various IDs.
# Output: Raw API JSON payloads.
# Chat name: Canvas SpeedGrader Archive
# AI Model: Claude Sonnet 4.6
# Attribution: Generated by Michael Gilchrist in collaboration with ChatGPT
#              and ClaudeAI Sonnet 4.6.

import pathlib
import time

from canvas_http import (
    http_delete,
    http_get_json,
    http_post_json,
    http_post_multipart_no_auth,
    http_put_json,
    paginated_get_all,
    paginated_get_all_list_key,
)


def get_quizzes(base_url, token, course_id, verbose=False):
    """GET all quizzes in a course."""
    url = f"{base_url}/api/v1/courses/{course_id}/quizzes?per_page=100"
    return paginated_get_all(url, token, verbose=verbose)


def get_quiz(base_url, token, course_id, quiz_id, verbose=False):
    """GET a single quiz object (title, points_possible, etc.)."""
    url = f"{base_url}/api/v1/courses/{course_id}/quizzes/{quiz_id}"
    if verbose:
        print(f"[GET] {url}")
    data, _headers = http_get_json(url, token)
    return data


def get_quiz_submissions(base_url, token, course_id, quiz_id, verbose=False):
    url = f"{base_url}/api/v1/courses/{course_id}/quizzes/{quiz_id}/submissions?include[]=quiz&per_page=100"
    # Canvas returns {"quiz_submissions":[...]} for this endpoint.
    return paginated_get_all_list_key(url, token, "quiz_submissions", verbose=verbose)


def get_quiz_questions(base_url, token, course_id, quiz_id, verbose=False):
    url = f"{base_url}/api/v1/courses/{course_id}/quizzes/{quiz_id}/questions"
    return paginated_get_all(url, token, verbose=verbose)


def get_submission_questions(base_url, token, submission_id, verbose=False):
    url = f"{base_url}/api/v1/quiz_submissions/{submission_id}/questions?include[]=quiz_question&per_page=100"
    # This endpoint typically returns a list; some instances may wrap it.
    return paginated_get_all_list_key(url, token, "quiz_submission_questions", verbose=verbose)


# ---- Quiz Reports (Student Analysis / Item Analysis) ----

def create_quiz_report(base_url, token, course_id, quiz_id,
                       report_type="student_analysis",
                       includes_all_versions=False, verbose=False):
    """POST to trigger generation of a quiz report.
    report_type: "student_analysis" or "item_analysis".
    Returns the QuizReport JSON object (includes progress_url when new).
    """
    url = (f"{base_url}/api/v1/courses/{course_id}"
           f"/quizzes/{quiz_id}/reports")
    body = {
        "quiz_report": {
            "report_type": report_type,
            "includes_all_versions": includes_all_versions,
        },
        "include": ["file", "progress"],
    }
    if verbose:
        print(f"[POST] {url}")
    data, _headers = http_post_json(url, token, body)
    return data


def get_quiz_report(base_url, token, course_id, quiz_id, report_id,
                    verbose=False):
    """GET a single quiz report, including the attached file object."""
    url = (f"{base_url}/api/v1/courses/{course_id}"
           f"/quizzes/{quiz_id}/reports/{report_id}?include[]=file")
    if verbose:
        print(f"[GET] {url}")
    data, _headers = http_get_json(url, token)
    return data


def get_progress(base_url, token, progress_id, verbose=False):
    """GET a Progress object by id (used for polling async jobs)."""
    url = f"{base_url}/api/v1/progress/{progress_id}"
    if verbose:
        print(f"[GET] {url}")
    data, _headers = http_get_json(url, token)
    return data


# ---- Courses ----

def get_courses(base_url, token, verbose=False):
    """GET all courses for the authenticated user, with term info."""
    url = (f"{base_url}/api/v1/courses"
           f"?per_page=100"
           f"&include[]=term"
           f"&include[]=total_students")
    return paginated_get_all(url, token, verbose=verbose)


# ---- Assignments ----

def get_assignment_groups(base_url, token, course_id, verbose=False):
    """GET all assignment groups (grading categories) in a course."""
    url = (f"{base_url}/api/v1/courses/{course_id}"
           f"/assignment_groups?per_page=100")
    return paginated_get_all(url, token, verbose=verbose)


def get_assignments(base_url, token, course_id, assignment_group_id=None,
                    verbose=False):
    """GET all assignments in a course, optionally filtered by group."""
    if assignment_group_id:
        url = (f"{base_url}/api/v1/courses/{course_id}"
               f"/assignment_groups/{assignment_group_id}"
               f"/assignments?per_page=100")
    else:
        url = (f"{base_url}/api/v1/courses/{course_id}"
               f"/assignments?per_page=100")
    return paginated_get_all(url, token, verbose=verbose)


def get_assignment(base_url, token, course_id, assignment_id, verbose=False):
    """GET a single assignment object."""
    url = (f"{base_url}/api/v1/courses/{course_id}"
           f"/assignments/{assignment_id}")
    if verbose:
        print(f"[GET] {url}")
    data, _headers = http_get_json(url, token)
    return data


def get_assignment_submissions(base_url, token, course_id, assignment_id,
                               verbose=False):
    """GET all submissions for an assignment with comments, rubric, history."""
    url = (f"{base_url}/api/v1/courses/{course_id}"
           f"/assignments/{assignment_id}/submissions"
           f"?per_page=100"
           f"&include[]=submission_comments"
           f"&include[]=rubric_assessment"
           f"&include[]=submission_history"
           f"&include[]=user"
           f"&include[]=group")
    return paginated_get_all(url, token, verbose=verbose)


def get_quiz_submission_data(base_url, token, course_id, assignment_id,
                             verbose=False):
    """GET assignment submissions with submission_history for quiz answer data.

    Each returned submission includes submission_history entries, each of
    which may contain submission_data (per-question answers, points, correct).
    Lighter weight than get_assignment_submissions() -- only includes
    submission_history and user info.
    """
    url = (f"{base_url}/api/v1/courses/{course_id}"
           f"/assignments/{assignment_id}/submissions"
           f"?per_page=100"
           f"&include[]=submission_history"
           f"&include[]=user")
    return paginated_get_all(url, token, verbose=verbose)


def get_rubric(base_url, token, course_id, rubric_id, verbose=False):
    """GET a rubric definition (criteria, ratings, descriptions)."""
    url = (f"{base_url}/api/v1/courses/{course_id}"
           f"/rubrics/{rubric_id}")
    if verbose:
        print(f"[GET] {url}")
    data, _headers = http_get_json(url, token)
    return data


# ---- Discussions ----

def get_discussion_topics(base_url, token, course_id, verbose=False):
    """GET all discussion topics in a course."""
    url = (f"{base_url}/api/v1/courses/{course_id}"
           f"/discussion_topics?per_page=100")
    return paginated_get_all(url, token, verbose=verbose)


def get_discussion_topic(base_url, token, course_id, topic_id,
                         verbose=False):
    """GET a single discussion topic object."""
    url = (f"{base_url}/api/v1/courses/{course_id}"
           f"/discussion_topics/{topic_id}")
    if verbose:
        print(f"[GET] {url}")
    data, _headers = http_get_json(url, token)
    return data


def get_discussion_topic_view(base_url, token, course_id, topic_id,
                              verbose=False):
    """GET the full threaded view of a discussion topic.

    Returns a dict with keys: participants, unread_entries,
    entry_ratings, forced_entries, view (nested entries), new_entries.
    This is a single non-paginated response.
    """
    url = (f"{base_url}/api/v1/courses/{course_id}"
           f"/discussion_topics/{topic_id}/view")
    if verbose:
        print(f"[GET] {url}")
    data, _headers = http_get_json(url, token)
    return data


# ---- Content Migrations (QTI Import) ----

def get_content_migration(base_url, token, course_id, migration_id,
                          verbose=False):
    """GET a single content migration by id (used for status polling)."""
    url = (f"{base_url}/api/v1/courses/{course_id}"
           f"/content_migrations/{migration_id}")
    if verbose:
        print(f"[GET] {url}")
    data, _headers = http_get_json(url, token)
    return data


def update_quiz(base_url, token, course_id, quiz_id, verbose=False, **fields):
    """PUT /api/v1/courses/:id/quizzes/:id to update quiz fields.

    Common fields: published (bool), position (int), title (str).
    Returns the updated quiz JSON dict.
    """
    url = f"{base_url}/api/v1/courses/{course_id}/quizzes/{quiz_id}"
    body = {"quiz": fields}
    if verbose:
        print(f"  [PUT] {url} {fields}")
    data, _ = http_put_json(url, token, body)
    return data


def delete_quiz(base_url, token, course_id, quiz_id, verbose=False):
    """DELETE /api/v1/courses/:id/quizzes/:id.

    Canvas returns 200 with the deleted quiz object on success.
    Raises urllib.error.HTTPError if the quiz has submissions (422).
    """
    url = f"{base_url}/api/v1/courses/{course_id}/quizzes/{quiz_id}"
    if verbose:
        print(f"  [DELETE] {url}")
    data, _ = http_delete(url, token)
    return data


def upload_qti_zip(base_url, token, course_id, zip_path,
                   poll_interval=5, verbose=False):
    """Upload a QTI zip file to Canvas via Content Migrations API.

    Workflow:
      1. POST /api/v1/courses/:id/content_migrations (initiate, get upload URL)
      2. POST the zip to pre_attachment.upload_url (no auth -- pre-authorized)
      3. Poll migration status until workflow_state is imported/completed/failed

    zip_path: str or pathlib.Path to the .zip file.
    Returns the final migration JSON dict on success.
    Raises RuntimeError on API or migration failure.
    """
    zip_path = pathlib.Path(zip_path)
    zip_data = zip_path.read_bytes()
    zip_size = len(zip_data)

    # Step 1: Initiate migration with file pre-attachment.
    url = f"{base_url}/api/v1/courses/{course_id}/content_migrations"
    body = {
        "migration_type": "qti_converter",
        "pre_attachment": {
            "name": zip_path.name,
            "size": zip_size,
            "content_type": "application/zip",
        },
    }
    if verbose:
        print(f"  [POST] {url}")
    migration, _ = http_post_json(url, token, body)

    migration_id = migration.get("id")
    if not migration_id:
        raise RuntimeError(
            f"No migration id in response: {migration}")
    if verbose:
        print(f"  [INFO] Migration id: {migration_id}, "
              f"state: {migration.get('workflow_state')}")

    # Step 2: Upload zip to the pre-signed/pre-authorized upload URL.
    pre = migration.get("pre_attachment")
    if not pre:
        raise RuntimeError(
            "No pre_attachment in migration response -- check that your "
            "Canvas token has 'Manage course content' permissions.")
    upload_url = pre.get("upload_url")
    if not upload_url:
        raise RuntimeError(f"No upload_url in pre_attachment: {pre}")

    upload_params = pre.get("upload_params", {})
    file_param = pre.get("file_param", "file")
    fields = {k: str(v) for k, v in upload_params.items()}
    files = {file_param: (zip_path.name, zip_data, "application/zip")}

    if verbose:
        print(f"  [INFO] Uploading {zip_size:,} bytes to: {upload_url}")
    http_post_multipart_no_auth(upload_url, fields, files)
    if verbose:
        print("  [INFO] Upload complete. Polling migration status...")

    # Step 3: Poll until finished.
    while True:
        data = get_content_migration(
            base_url, token, course_id, migration_id, verbose=False)
        state = data.get("workflow_state", "")
        if verbose:
            print(f"  [INFO] Migration state: {state}")
        if state in ("imported", "completed"):
            return data
        if state == "failed":
            issues = data.get("migration_issues_count", 0)
            raise RuntimeError(
                f"Migration {migration_id} failed "
                f"({issues} issue(s)). "
                f"Check: {base_url}/courses/{course_id}/content_migrations")
        time.sleep(poll_interval)
