#!/usr/bin/env python3
# ============================================================================
# Script:       canvas.api.list_discussions.py
# Version:      1.0.0
# Date:         2026-02-20
# Purpose:      List all discussion topics in a Canvas course with ID,
#               published status, post date, reply count, due date, and title.
#
# Usage:        canvas.api.list_discussions.py COURSE_ID
#                   [--base-url URL] [--token TOKEN | --token-file FILE]
#                   [--published-only] [--dry-run] [--verbose] [--help]
#
# Input:        Canvas API token + course_id (or ~/.canvas.api.conf)
# Output:       Tabular discussion topic listing to stdout
#
# Options:
#   --base-url URL          Canvas instance URL (or set in ~/.canvas.api.conf)
#   --token TOKEN           Inline API token
#   --token-file FILE       Path to token file (or set in ~/.canvas.api.conf)
#   --published-only        Only show published topics
#   -n, --dry-run           Show the API URL that would be fetched
#   -v, --verbose           Show detailed output
#   -h, --help              Show this help message
#
# Session:      Canvas.API
# AI Model:     Claude Opus 4.6
# Attribution:  Generated by Michael Gilchrist in collaboration with
#               ClaudeAI Opus 4.6
# ============================================================================

import argparse

from canvas_api import get_discussion_topics
from io_utils import load_profile, read_token


def main():
    ap = argparse.ArgumentParser(
        description="List all discussion topics in a Canvas course.")
    ap.add_argument("course_id", type=int,
                    help="Canvas course ID")

    ap.add_argument("--base-url", default=None,
                    help="Canvas instance URL (or set base_url in "
                         "~/.canvas.api.conf)")
    ap.add_argument("--token", default=None,
                    help="Canvas API token (inline)")
    ap.add_argument("--token-file", default=None,
                    help="Path to token file (or set token_file in "
                         "~/.canvas.api.conf)")

    ap.add_argument("--published-only", action="store_true",
                    help="Only show published topics")
    ap.add_argument("-n", "--dry-run", action="store_true",
                    help="Show the API URL that would be fetched")
    ap.add_argument("-v", "--verbose", action="store_true",
                    help="Show detailed output")

    args = ap.parse_args()

    profile = load_profile()
    if not args.base_url:
        args.base_url = profile.get("base_url")
    if not args.base_url:
        ap.error("--base-url is required (or set base_url in "
                 "~/.canvas.api.conf)")
    token = read_token(args.token, args.token_file, profile)
    base_url = args.base_url.rstrip("/")

    # Dry-run: show what would be fetched and exit
    if args.dry_run:
        url = (f"{base_url}/api/v1/courses/{args.course_id}"
               f"/discussion_topics?per_page=100")
        print(f"[DRY RUN] Would fetch: {url}")
        return

    if args.verbose:
        print(f"[INFO] Fetching discussion topics for course "
              f"{args.course_id}...")

    topics = get_discussion_topics(base_url, token, args.course_id,
                                   verbose=args.verbose)

    if args.published_only:
        topics = [t for t in topics if t.get("published")]

    # Sort by title for readability
    topics.sort(key=lambda t: t.get("title", ""))

    if not topics:
        print("No discussion topics found.")
        return

    # Print table header
    print(f"{'ID':>8}  {'Pub':>3}  {'Replies':>7}  "
          f"{'Posted':<11}  {'Due':<11}  Title")
    print(f"{'---':>8}  {'---':>3}  {'---':>7}  "
          f"{'---':<11}  {'---':<11}  ---")

    for t in topics:
        tid = t.get("id", "")
        title = t.get("title", "(untitled)")
        published = "yes" if t.get("published") else "no"
        replies = t.get("discussion_subentry_count", 0)
        posted = t.get("posted_at", "") or ""
        posted_str = posted[:10] if posted else "-"
        due = ""
        # due_at may be on the topic or in assignment overrides
        assignment = t.get("assignment")
        if assignment and isinstance(assignment, dict):
            due = assignment.get("due_at", "") or ""
        if not due:
            due = t.get("delayed_post_at", "") or ""
        due_str = due[:10] if due else "-"

        print(f"{tid:>8}  {published:>3}  {replies:>7}  "
              f"{posted_str:<11}  {due_str:<11}  {title}")

    print(f"\nTotal: {len(topics)} discussion topics")


if __name__ == "__main__":
    main()
