#!/usr/bin/env python3
#
# Date: 2026-02-19
# Version: 1.2.0
# Purpose: Minimal Canvas API endpoint wrappers used for Classic Quiz response extraction.
# Usage: Imported by api_to_json.py.
# Input: Canvas base URL, token, course_id, quiz_id, submission_id.
# Output: Raw API JSON payloads.
# Chat name: Canvas SpeedGrader Archive
# GPT Model: GPT-5.2 Thinking
# Attribution: Generated by Michael Gilchrist in collaboration with ChatGPT.

from canvas_http import (
    http_get_json,
    http_post_json,
    paginated_get_all,
    paginated_get_all_list_key,
)


def get_quizzes(base_url, token, course_id, verbose=False):
    """GET all quizzes in a course."""
    url = f"{base_url}/api/v1/courses/{course_id}/quizzes?per_page=100"
    return paginated_get_all(url, token, verbose=verbose)


def get_quiz(base_url, token, course_id, quiz_id, verbose=False):
    """GET a single quiz object (title, points_possible, etc.)."""
    url = f"{base_url}/api/v1/courses/{course_id}/quizzes/{quiz_id}"
    if verbose:
        print(f"[GET] {url}")
    data, _headers = http_get_json(url, token)
    return data


def get_quiz_submissions(base_url, token, course_id, quiz_id, verbose=False):
    url = f"{base_url}/api/v1/courses/{course_id}/quizzes/{quiz_id}/submissions?include[]=quiz&per_page=100"
    # Canvas returns {"quiz_submissions":[...]} for this endpoint.
    return paginated_get_all_list_key(url, token, "quiz_submissions", verbose=verbose)


def get_quiz_questions(base_url, token, course_id, quiz_id, verbose=False):
    url = f"{base_url}/api/v1/courses/{course_id}/quizzes/{quiz_id}/questions"
    return paginated_get_all(url, token, verbose=verbose)


def get_submission_questions(base_url, token, submission_id, verbose=False):
    url = f"{base_url}/api/v1/quiz_submissions/{submission_id}/questions?include[]=quiz_question&per_page=100"
    # This endpoint typically returns a list; some instances may wrap it.
    return paginated_get_all_list_key(url, token, "quiz_submission_questions", verbose=verbose)


# ---- Quiz Reports (Student Analysis / Item Analysis) ----

def create_quiz_report(base_url, token, course_id, quiz_id,
                       report_type="student_analysis",
                       includes_all_versions=False, verbose=False):
    """POST to trigger generation of a quiz report.
    report_type: "student_analysis" or "item_analysis".
    Returns the QuizReport JSON object (includes progress_url when new).
    """
    url = (f"{base_url}/api/v1/courses/{course_id}"
           f"/quizzes/{quiz_id}/reports")
    body = {
        "quiz_report": {
            "report_type": report_type,
            "includes_all_versions": includes_all_versions,
        },
        "include": ["file", "progress"],
    }
    if verbose:
        print(f"[POST] {url}")
    data, _headers = http_post_json(url, token, body)
    return data


def get_quiz_report(base_url, token, course_id, quiz_id, report_id,
                    verbose=False):
    """GET a single quiz report, including the attached file object."""
    url = (f"{base_url}/api/v1/courses/{course_id}"
           f"/quizzes/{quiz_id}/reports/{report_id}?include[]=file")
    if verbose:
        print(f"[GET] {url}")
    data, _headers = http_get_json(url, token)
    return data


def get_progress(base_url, token, progress_id, verbose=False):
    """GET a Progress object by id (used for polling async jobs)."""
    url = f"{base_url}/api/v1/progress/{progress_id}"
    if verbose:
        print(f"[GET] {url}")
    data, _headers = http_get_json(url, token)
    return data
