#!/usr/bin/env python3
# ============================================================================
# Script:       canvas.api.update_lecture_page.py
# Version:      1.0.0
# Date:         2026-03-01
# Purpose:      Update the Quiz and/or Slides section of a Canvas session
#               page (e.g. S12) with links to the published quiz and/or
#               uploaded slides PDF.
#
#               Session pages follow this structure:
#                 <h3>Reading[s]</h3>  -- not touched
#                 <h3>Quiz</h3>        -- updated by --quiz-id
#                 <h3>Slides</h3>      -- updated by --slides or --slides-id
#
#               Links are generated in Canvas's native HTML format so they
#               render correctly (quiz link with data-api-* attrs; file link
#               with verifier token and instructure_file_link class).
#
# Usage:        canvas.api.update_lecture_page.py COURSE_ID SESSION
#                   [--quiz-id QUIZ_ID]
#                   [--slides FILENAME | --slides-id FILE_ID]
#                   [--base-url URL] [--token TOKEN | --token-file FILE]
#                   [--dry-run] [--verbose] [--help]
#
# Input:        Canvas course ID; session prefix (e.g. S12 or S06a)
# Output:       Updated page URL and change summary on stdout
#
# Options:
#   SESSION              Session prefix, e.g. S12 or S06a
#   --quiz-id QUIZ_ID    Canvas quiz ID to link in the Quiz section
#   --slides FILENAME    Search Canvas files by filename to link in Slides
#   --slides-id FILE_ID  Use known Canvas file ID for slides link
#   --base-url URL       Canvas instance URL (or set in ~/.canvas.api.conf)
#   --token TOKEN        Inline API token
#   --token-file FILE    Path to file containing API token
#   -n, --dry-run        Show current and proposed section content without
#                        making changes
#   -v, --verbose        Show detailed output
#   -h, --help           Show this help message
#
# Requirements:
#   - Python 3.7+
#   - Canvas API token with page edit permissions
#   - ~/.canvas.api.conf with base_url and token_file (or pass via CLI)
#
# Session:      S12 Stem Cells QTI Import
# AI Model:     Claude Sonnet 4.6
# Attribution:  Generated by Michael Gilchrist in collaboration with
#               ClaudeAI Sonnet 4.6
# ============================================================================

import argparse
import os
import re
import sys

sys.path.insert(0, os.path.dirname(__file__))

from canvas_api import (
    get_file,
    get_page,
    get_pages,
    get_quiz,
    search_files,
    update_page,
)
from io_utils import load_profile, read_token


# ---- Session prefix utilities (shared with other scripts) ----

def extract_session_prefix(title):
    """Extract 'S12' or 'S06a' from 'S12: 2026-03-03 - Topic'."""
    if not title:
        return ""
    m = re.match(r'^(S\d+[a-d]?)\s*:', title, re.IGNORECASE)
    return m.group(1).upper() if m else ""


# ---- HTML section manipulation ----

def get_section_content(html, section_name):
    """Return the content between <h3>SECTION</h3> and the next <h3> or EOF.
    Returns None if the section is not found.
    """
    pattern = (rf'<h3>\s*{re.escape(section_name)}\s*</h3>'
               rf'(.*?)(?=<h3>|$)')
    m = re.search(pattern, html, re.DOTALL | re.IGNORECASE)
    return m.group(1).strip() if m else None


def replace_section_content(html, section_name, new_content):
    """Replace the content of <h3>SECTION</h3> ... (next <h3>|end) with
    new_content.  The <h3> header itself is preserved.
    Returns (new_html, was_found).
    """
    pattern = (rf'(<h3>\s*{re.escape(section_name)}\s*</h3>)'
               rf'(.*?)(?=<h3>|$)')

    found = [False]

    def _replace(m):
        found[0] = True
        return m.group(1) + "\n" + new_content + "\n"

    new_html = re.sub(pattern, _replace, html,
                      flags=re.DOTALL | re.IGNORECASE)
    return new_html, found[0]


# ---- Canvas HTML generators ----

def quiz_html(base_url, course_id, quiz_id, quiz_title, published):
    """Generate a Canvas-style quiz link paragraph."""
    pub = "true" if published else "false"
    href = f"{base_url}/courses/{course_id}/quizzes/{quiz_id}"
    api_ep = f"{base_url}/api/v1/courses/{course_id}/quizzes/{quiz_id}"
    return (
        f'<p><a title="{_hesc(quiz_title)}" href="{href}" '
        f'data-course-type="quizzes" data-published="{pub}" '
        f'data-api-endpoint="{api_ep}" '
        f'data-api-returntype="Quiz">{_hesc(quiz_title)}</a></p>'
    )


def file_html(base_url, course_id, file_id, file_data):
    """Generate a Canvas-style file link paragraph using file metadata."""
    name = file_data.get("display_name") or file_data.get("filename", "")
    raw_url = file_data.get("url", "")  # includes verifier
    href = raw_url.replace("&", "&amp;")
    api_ep = f"{base_url}/api/v1/courses/{course_id}/files/{file_id}"
    return (
        f'<p><a class="instructure_file_link instructure_scribd_file '
        f'inline_disabled" title="{_hesc(name)}" href="{href}" '
        f'target="_blank" data-canvas-previewable="false" '
        f'data-api-endpoint="{api_ep}" '
        f'data-api-returntype="File">{_hesc(name)}</a></p>'
    )


def _hesc(s):
    """Minimal HTML attribute escaping for title/text content."""
    return (s.replace("&", "&amp;")
             .replace('"', "&quot;")
             .replace("<", "&lt;")
             .replace(">", "&gt;"))


# ---- Page discovery ----

def find_page_for_session(pages, session_prefix):
    """Find pages whose title matches a session prefix (e.g. 'S12').
    Returns a list of matching page dicts.
    """
    prefix_upper = session_prefix.upper()
    return [p for p in pages
            if extract_session_prefix(p.get("title", "")) == prefix_upper]


# ---- Main ----

def main():
    ap = argparse.ArgumentParser(
        description="Update the Quiz and/or Slides section of a Canvas "
                    "session page with links to the published quiz and/or "
                    "slides PDF.")
    ap.add_argument("course_id", type=int,
                    help="Canvas course ID")
    ap.add_argument("session", metavar="SESSION",
                    help="Session prefix, e.g. S12 or S06a")
    ap.add_argument("--quiz-id", type=int, default=None,
                    help="Canvas quiz ID to link in the Quiz section")
    ap.add_argument("--slides", default=None, metavar="FILENAME",
                    help="Search Canvas files by filename to link in Slides "
                         "section")
    ap.add_argument("--slides-id", type=int, default=None,
                    help="Canvas file ID for slides (use instead of "
                         "--slides)")
    ap.add_argument("--base-url", default=None,
                    help="Canvas instance URL (or set base_url in "
                         "~/.canvas.api.conf)")
    ap.add_argument("--token", default=None,
                    help="Canvas API token (inline)")
    ap.add_argument("--token-file", default=None,
                    help="Path to file containing API token")
    ap.add_argument("-n", "--dry-run", action="store_true",
                    help="Show current and proposed section content without "
                         "writing changes")
    ap.add_argument("-v", "--verbose", action="store_true",
                    help="Show detailed output")
    args = ap.parse_args()

    if not args.quiz_id and not args.slides and not args.slides_id:
        ap.error("Provide at least one of --quiz-id, --slides, or "
                 "--slides-id")
    if args.slides and args.slides_id:
        ap.error("Use --slides or --slides-id, not both")

    profile = load_profile()
    if not args.base_url:
        args.base_url = profile.get("base_url")
    if not args.base_url:
        ap.error("--base-url is required (or set base_url in "
                 "~/.canvas.api.conf)")
    base_url = args.base_url.rstrip("/")
    token = read_token(args.token, args.token_file, profile)

    session_prefix = args.session.upper()
    print(f"Session : {session_prefix}")
    print(f"Course  : {args.course_id}")

    # Find the session page.
    if args.verbose:
        print("Fetching page list...")
    pages = get_pages(base_url, token, args.course_id, verbose=args.verbose)
    matches = find_page_for_session(pages, session_prefix)

    if not matches:
        print(f"[FAIL] No page found with title starting '{session_prefix}:'",
              file=sys.stderr)
        sys.exit(1)
    if len(matches) > 1:
        print(f"[WARN] Multiple pages match {session_prefix!r}:")
        for p in matches:
            print(f"  {p['url']!r}: {p['title']!r}")
        print("Disambiguate or check page titles.", file=sys.stderr)
        sys.exit(1)

    page_meta = matches[0]
    page_url = page_meta["url"]
    print(f"Page    : {page_meta['title']!r}  ({page_url})")

    # Fetch full page HTML.
    page = get_page(base_url, token, args.course_id, page_url,
                    verbose=args.verbose)
    html = page.get("body") or ""

    # --- Quiz section ---
    quiz_new_html = None
    if args.quiz_id:
        quiz_data = get_quiz(base_url, token, args.course_id, args.quiz_id,
                             verbose=args.verbose)
        q_title = quiz_data.get("title", f"Quiz {args.quiz_id}")
        q_pub = quiz_data.get("published", False)
        quiz_new_html = quiz_html(base_url, args.course_id, args.quiz_id,
                                  q_title, q_pub)
        print(f"Quiz    : id={args.quiz_id}, {q_title!r}, "
              f"published={q_pub}")

    # --- Slides section ---
    slides_new_html = None
    if args.slides_id or args.slides:
        if args.slides_id:
            file_id = args.slides_id
            fdata = get_file(base_url, token, args.course_id, file_id,
                             verbose=args.verbose)
        else:
            results = search_files(base_url, token, args.course_id,
                                   args.slides, verbose=args.verbose)
            if not results:
                print(f"[FAIL] No Canvas file found matching "
                      f"{args.slides!r}", file=sys.stderr)
                sys.exit(1)
            if len(results) > 1:
                print(f"[WARN] Multiple files match {args.slides!r}:")
                for f in results:
                    print(f"  id={f['id']}: {f.get('display_name')!r}")
                print("Use --slides-id to specify one.", file=sys.stderr)
                sys.exit(1)
            fdata = results[0]
            file_id = fdata["id"]

        fname = fdata.get("display_name") or fdata.get("filename", "")
        slides_new_html = file_html(base_url, args.course_id, file_id, fdata)
        print(f"Slides  : id={file_id}, {fname!r}")

    # --- Apply updates ---
    new_html = html
    changed = False

    if quiz_new_html:
        current = get_section_content(new_html, "Quiz")
        if args.dry_run:
            print("\n[DRY RUN] Quiz section -- current:")
            print(f"  {(current or '').strip()!r}")
            print("[DRY RUN] Quiz section -- proposed:")
            print(f"  {quiz_new_html!r}")
        else:
            new_html, found = replace_section_content(
                new_html, "Quiz", quiz_new_html)
            if not found:
                print("[WARN] <h3>Quiz</h3> section not found in page body.",
                      file=sys.stderr)
            else:
                changed = True
                print("[OK] Quiz section updated.")

    if slides_new_html:
        current = get_section_content(new_html, "Slides")
        if args.dry_run:
            print("\n[DRY RUN] Slides section -- current:")
            print(f"  {(current or '').strip()!r}")
            print("[DRY RUN] Slides section -- proposed:")
            print(f"  {slides_new_html!r}")
        else:
            new_html, found = replace_section_content(
                new_html, "Slides", slides_new_html)
            if not found:
                print("[WARN] <h3>Slides</h3> section not found in page body.",
                      file=sys.stderr)
            else:
                changed = True
                print("[OK] Slides section updated.")

    if args.dry_run:
        return

    if not changed:
        print("No sections updated.")
        return

    update_page(base_url, token, args.course_id, page_url, new_html,
                verbose=args.verbose)
    print(f"\nPage    : {base_url}/courses/{args.course_id}"
          f"/pages/{page_url}")


if __name__ == "__main__":
    main()
