#!/usr/bin/env python3
# ============================================================================
# Script:       canvas.api.upload_quiz.py
# Version:      1.0.0
# Date:         2026-03-01
# Purpose:      Upload a QTI zip to Canvas as a Classic Quiz, position it
#               by session order among published quizzes, and optionally
#               publish it.  Offers to delete any existing quiz with the
#               same session prefix (e.g., an old S12 from 2025).
#
# Workflow:
#   1. Read quiz title from the QTI zip (assessment_meta.xml)
#   2. Snapshot existing quiz IDs
#   3. Upload zip via Content Migrations API and poll until complete
#   4. Identify the new quiz by diffing quiz lists
#   5. Check for existing quizzes with the same session prefix; offer to delete
#   6. Position the new quiz after the last published quiz of lower/equal
#      session number (not at the bottom as Canvas does by default)
#   7. Optionally publish
#
# Usage:        canvas.api.upload_quiz.py COURSE_ID QTI_ZIP
#                   [--publish] [--yes]
#                   [--base-url URL] [--token TOKEN | --token-file FILE]
#                   [--poll-interval SEC] [--dry-run] [--verbose] [--help]
#
# Input:        A QTI zip file (e.g., from text2qti) and a Canvas course ID
# Output:       Upload/positioning status and quiz URL on stdout
#
# Options:
#   --publish              Publish the quiz after upload
#   --yes                  Auto-confirm deletion of old same-prefix quiz
#   --base-url URL         Canvas instance URL (or set in ~/.canvas.api.conf)
#   --token TOKEN          Inline API token
#   --token-file FILE      Path to file containing API token
#   --poll-interval SEC    Seconds between migration status polls (default: 5)
#   -n, --dry-run          Show what would be done without uploading
#   -v, --verbose          Show detailed output
#   -h, --help             Show this help message
#
# Requirements:
#   - Python 3.7+
#   - Canvas API token with 'Manage course content' permission
#   - ~/.canvas.api.conf with base_url and token_file (or pass via CLI)
#
# Session:      S12 Stem Cells QTI Import
# AI Model:     Claude Sonnet 4.6
# Attribution:  Generated by Michael Gilchrist in collaboration with
#               ClaudeAI Sonnet 4.6
# ============================================================================

import argparse
import os
import re
import sys
import xml.etree.ElementTree as ET
import zipfile

sys.path.insert(0, os.path.dirname(__file__))

from canvas_api import delete_quiz, get_quizzes, update_quiz, upload_qti_zip
from io_utils import load_profile, read_token


# ---- QTI zip introspection ----

def read_qti_title(zip_path):
    """Extract quiz title from a text2qti QTI zip (reads assessment_meta.xml).
    Returns the title string, or None if not found.
    """
    with zipfile.ZipFile(zip_path) as zf:
        for name in zf.namelist():
            if name.endswith("assessment_meta.xml"):
                with zf.open(name) as f:
                    tree = ET.parse(f)
                    root = tree.getroot()
                    for elem in root:
                        # Strip namespace prefix (e.g. {http://...}title)
                        tag = (elem.tag.split("}")[-1]
                               if "}" in elem.tag else elem.tag)
                        if tag == "title":
                            return elem.text
    return None


# ---- Session prefix utilities ----

def extract_session_prefix(title):
    """Extract 'S12' or 'S06a' from 'S12: 2026-03-03 - Topic'.
    Returns uppercase prefix string, or '' if not found.
    """
    if not title:
        return ""
    m = re.match(r'^(S\d+[a-d]?)\s*:', title, re.IGNORECASE)
    return m.group(1).upper() if m else ""


def session_sort_key(prefix):
    """Return (number, letter) sort key for prefixes like 'S12', 'S06a'."""
    if not prefix:
        return (999, "")
    m = re.match(r'^S(\d+)([a-d]?)$', prefix, re.IGNORECASE)
    if not m:
        return (999, "")
    return (int(m.group(1)), m.group(2).lower())


# ---- Positioning ----

def compute_target_position(quizzes, new_title, new_quiz_id):
    """Return the 1-based Canvas position for the new quiz.

    Inserts the quiz after the last PUBLISHED quiz whose session prefix
    is <= the new quiz's prefix, keeping active quizzes in session order.
    If no published quizzes precede this one, returns 1.
    """
    new_key = session_sort_key(extract_session_prefix(new_title))

    # Only consider published quizzes other than the new one itself.
    published = [
        q for q in quizzes
        if q.get("published", False) and q.get("id") != new_quiz_id
    ]
    published_sorted = sorted(published, key=lambda q: q.get("position", 999))

    last_pos = 0
    for q in published_sorted:
        q_key = session_sort_key(extract_session_prefix(q.get("title", "")))
        if q_key <= new_key:
            last_pos = q.get("position", 0)
    return last_pos + 1


# ---- Prompting ----

def prompt_yes_no(message, auto_yes=False):
    """Print message and ask y/n.  Returns True for yes."""
    if auto_yes:
        print(f"{message} [auto-yes]")
        return True
    if not sys.stdin.isatty():
        print(f"{message} [non-interactive: skipping]")
        return False
    ans = input(f"{message} [y/N] ").strip().lower()
    return ans in ("y", "yes")


# ---- Main ----

def main():
    ap = argparse.ArgumentParser(
        description="Upload a QTI zip to Canvas as a Classic Quiz, position "
                    "it by session order among published quizzes, and "
                    "optionally publish it.")
    ap.add_argument("course_id", type=int,
                    help="Canvas course ID")
    ap.add_argument("qti_zip", metavar="QTI_ZIP",
                    help="Path to the QTI zip file")
    ap.add_argument("--publish", action="store_true",
                    help="Publish the quiz after upload")
    ap.add_argument("--yes", "-y", action="store_true",
                    help="Auto-confirm deletion of existing quiz with same "
                         "session prefix")
    ap.add_argument("--base-url", default=None,
                    help="Canvas instance URL (or set base_url in "
                         "~/.canvas.api.conf)")
    ap.add_argument("--token", default=None,
                    help="Canvas API token (inline)")
    ap.add_argument("--token-file", default=None,
                    help="Path to file containing API token")
    ap.add_argument("--poll-interval", type=int, default=5,
                    help="Seconds between migration status polls (default: 5)")
    ap.add_argument("-n", "--dry-run", action="store_true",
                    help="Show what would be done without uploading")
    ap.add_argument("-v", "--verbose", action="store_true",
                    help="Show detailed output")
    args = ap.parse_args()

    profile = load_profile()
    if not args.base_url:
        args.base_url = profile.get("base_url")
    if not args.base_url:
        ap.error("--base-url is required (or set base_url in "
                 "~/.canvas.api.conf)")
    base_url = args.base_url.rstrip("/")
    token = read_token(args.token, args.token_file, profile)

    if not os.path.isfile(args.qti_zip):
        ap.error(f"File not found: {args.qti_zip}")
    size = os.path.getsize(args.qti_zip)
    filename = os.path.basename(args.qti_zip)

    # Read title from zip before uploading so we know the session prefix.
    title = read_qti_title(args.qti_zip)
    session_prefix = extract_session_prefix(title) if title else ""

    print(f"QTI zip : {filename} ({size:,} bytes)")
    print(f"Title   : {title or '(could not read from zip)'}")
    print(f"Session : {session_prefix or '(none detected)'}")
    print(f"Course  : {args.course_id}")
    print(f"Canvas  : {base_url}")
    if args.publish:
        print("Publish : yes (--publish)")

    if args.dry_run:
        print(f"[DRY RUN] Would POST to "
              f"{base_url}/api/v1/courses/{args.course_id}"
              f"/content_migrations")
        return

    # Snapshot existing quiz IDs so we can identify the newly created quiz.
    if args.verbose:
        print("Fetching pre-upload quiz snapshot...")
    quizzes_before = get_quizzes(base_url, token, args.course_id,
                                 verbose=args.verbose)
    ids_before = {q["id"] for q in quizzes_before}

    # Upload.
    print("Uploading...")
    try:
        migration = upload_qti_zip(
            base_url=base_url,
            token=token,
            course_id=args.course_id,
            zip_path=args.qti_zip,
            poll_interval=args.poll_interval,
            verbose=args.verbose,
        )
    except Exception as e:
        print(f"[FAIL] Upload failed: {e}", file=sys.stderr)
        sys.exit(1)

    migration_id = migration.get("id")
    print(f"[OK] Migration {migration_id} complete.")

    # Identify the new quiz by diffing quiz lists.
    quizzes_after = get_quizzes(base_url, token, args.course_id,
                                verbose=args.verbose)
    new_quizzes = [q for q in quizzes_after if q["id"] not in ids_before]

    if not new_quizzes:
        print("[WARN] Could not identify new quiz (no new quiz IDs found). "
              "Check Canvas manually.", file=sys.stderr)
        print(f"Quizzes: {base_url}/courses/{args.course_id}/quizzes")
        return

    if len(new_quizzes) > 1:
        print(f"[WARN] {len(new_quizzes)} new quizzes found; using the first.",
              file=sys.stderr)

    new_quiz = new_quizzes[0]
    new_quiz_id = new_quiz["id"]
    new_quiz_title = new_quiz.get("title", title or "")
    print(f"New quiz: id={new_quiz_id}, title={new_quiz_title!r}")

    # Check for existing quizzes with the same session prefix.
    if session_prefix:
        old_quizzes = [
            q for q in quizzes_after
            if q["id"] != new_quiz_id
            and extract_session_prefix(q.get("title", "")) == session_prefix
        ]
        if old_quizzes:
            print(f"\nFound {len(old_quizzes)} existing quiz(es) with "
                  f"prefix {session_prefix!r}:")
            for q in old_quizzes:
                status = "published" if q.get("published") else "unpublished"
                print(f"  id={q['id']}: {q.get('title')!r} ({status})")
            for q in old_quizzes:
                if prompt_yes_no(
                        f"Delete id={q['id']}: {q.get('title')!r}?",
                        auto_yes=args.yes):
                    try:
                        delete_quiz(base_url, token, args.course_id, q["id"],
                                    verbose=args.verbose)
                        print(f"  [DELETED] {q['id']}")
                        # Remove from working list so position calc is correct.
                        quizzes_after = [
                            x for x in quizzes_after if x["id"] != q["id"]]
                    except Exception as e:
                        print(f"  [WARN] Could not delete {q['id']}: {e}",
                              file=sys.stderr)

    # Position the quiz after the last published quiz of lower/equal session.
    target_pos = compute_target_position(
        quizzes_after, new_quiz_title, new_quiz_id)
    if args.verbose:
        print(f"Setting position to {target_pos}...")
    try:
        update_quiz(base_url, token, args.course_id, new_quiz_id,
                    verbose=args.verbose, position=target_pos)
        print(f"Position: {target_pos}")
    except Exception as e:
        print(f"[WARN] Could not set position: {e}", file=sys.stderr)

    # Publish if requested.
    if args.publish:
        try:
            update_quiz(base_url, token, args.course_id, new_quiz_id,
                        verbose=args.verbose, published=True)
            print("Published: yes")
        except Exception as e:
            print(f"[WARN] Could not publish: {e}", file=sys.stderr)

    issue_count = migration.get("migration_issues_count", 0)
    if issue_count:
        print(f"[WARN] {issue_count} migration issue(s). "
              f"Check: {base_url}/courses/{args.course_id}/content_migrations")

    print(f"\nDone.")
    print(f"Quiz    : {base_url}/courses/{args.course_id}"
          f"/quizzes/{new_quiz_id}")
    print(f"All     : {base_url}/courses/{args.course_id}/quizzes")


if __name__ == "__main__":
    main()
