#!/usr/bin/env python3
# ============================================================================
# Script:       canvas.api.publish_quiz.py
# Version:      1.0.0
# Date:         2026-03-01
# Purpose:      Publish or unpublish a Canvas Classic Quiz by ID or by
#               session prefix / title substring search.
#
# Usage:        canvas.api.publish_quiz.py COURSE_ID QUIZ_ID [--unpublish]
#           OR  canvas.api.publish_quiz.py COURSE_ID --title S12 [--unpublish]
#                   [--base-url URL] [--token TOKEN | --token-file FILE]
#                   [--dry-run] [--verbose] [--help]
#
# Input:        Canvas course ID and quiz ID (or title search pattern)
# Output:       Publish status on stdout
#
# Options:
#   QUIZ_ID                Canvas quiz ID (numeric)
#   --title PATTERN        Session prefix (e.g. 'S12') or title substring
#                          to find the quiz; use instead of QUIZ_ID
#   --unpublish            Unpublish instead of publish (default: publish)
#   --base-url URL         Canvas instance URL (or set in ~/.canvas.api.conf)
#   --token TOKEN          Inline API token
#   --token-file FILE      Path to file containing API token
#   -n, --dry-run          Show what would be done without making changes
#   -v, --verbose          Show detailed output
#   -h, --help             Show this help message
#
# Requirements:
#   - Python 3.7+
#   - Canvas API token with quiz edit permissions
#   - ~/.canvas.api.conf with base_url and token_file (or pass via CLI)
#
# Session:      S12 Stem Cells QTI Import
# AI Model:     Claude Sonnet 4.6
# Attribution:  Generated by Michael Gilchrist in collaboration with
#               ClaudeAI Sonnet 4.6
# ============================================================================

import argparse
import os
import re
import sys

sys.path.insert(0, os.path.dirname(__file__))

from canvas_api import get_quizzes, update_quiz
from io_utils import load_profile, read_token


def extract_session_prefix(title):
    """Extract 'S12' or 'S06a' from 'S12: 2026-03-03 - Topic'."""
    if not title:
        return ""
    m = re.match(r'^(S\d+[a-d]?)\s*:', title, re.IGNORECASE)
    return m.group(1).upper() if m else ""


def find_quizzes_by_pattern(quizzes, pattern):
    """Find quizzes matching a session prefix (e.g. 'S12') or title substring.

    Session prefix match is tried first (exact, case-insensitive).
    Falls back to substring match on the full title.
    Returns a list of matching quiz dicts.
    """
    pattern_upper = pattern.upper()
    # Try session prefix match first.
    by_prefix = [
        q for q in quizzes
        if extract_session_prefix(q.get("title", "")) == pattern_upper
    ]
    if by_prefix:
        return by_prefix
    # Fall back to substring match.
    pattern_lower = pattern.lower()
    return [q for q in quizzes if pattern_lower in q.get("title", "").lower()]


def main():
    ap = argparse.ArgumentParser(
        description="Publish or unpublish a Canvas Classic Quiz.")
    ap.add_argument("course_id", type=int,
                    help="Canvas course ID")
    ap.add_argument("quiz_id", nargs="?", type=int, default=None,
                    help="Canvas quiz ID (numeric); use --title instead for "
                         "search by prefix")
    ap.add_argument("--title", default=None, metavar="PATTERN",
                    help="Session prefix (e.g. 'S12') or title substring to "
                         "locate the quiz; use instead of QUIZ_ID")
    ap.add_argument("--unpublish", action="store_true",
                    help="Unpublish the quiz (default: publish)")
    ap.add_argument("--base-url", default=None,
                    help="Canvas instance URL (or set base_url in "
                         "~/.canvas.api.conf)")
    ap.add_argument("--token", default=None,
                    help="Canvas API token (inline)")
    ap.add_argument("--token-file", default=None,
                    help="Path to file containing API token")
    ap.add_argument("-n", "--dry-run", action="store_true",
                    help="Show what would be done without making changes")
    ap.add_argument("-v", "--verbose", action="store_true",
                    help="Show detailed output")
    args = ap.parse_args()

    if args.quiz_id is None and args.title is None:
        ap.error("Provide a QUIZ_ID argument or --title PATTERN")
    if args.quiz_id is not None and args.title is not None:
        ap.error("Provide QUIZ_ID or --title, not both")

    profile = load_profile()
    if not args.base_url:
        args.base_url = profile.get("base_url")
    if not args.base_url:
        ap.error("--base-url is required (or set base_url in "
                 "~/.canvas.api.conf)")
    base_url = args.base_url.rstrip("/")
    token = read_token(args.token, args.token_file, profile)

    action = "Unpublish" if args.unpublish else "Publish"
    target_state = not args.unpublish  # True = publish, False = unpublish

    # Resolve quiz by title search if needed.
    if args.title:
        all_quizzes = get_quizzes(base_url, token, args.course_id,
                                  verbose=args.verbose)
        matches = find_quizzes_by_pattern(all_quizzes, args.title)
        if not matches:
            print(f"[FAIL] No quiz found matching {args.title!r}",
                  file=sys.stderr)
            sys.exit(1)
        if len(matches) > 1:
            print(f"[WARN] Multiple matches for {args.title!r}:")
            for q in matches:
                status = "published" if q.get("published") else "unpublished"
                print(f"  id={q['id']}: {q.get('title')!r} ({status})")
            print("Specify a quiz ID to disambiguate.", file=sys.stderr)
            sys.exit(1)
        quiz = matches[0]
        quiz_id = quiz["id"]
        quiz_title = quiz.get("title", "")
        current = "published" if quiz.get("published") else "unpublished"
    else:
        quiz_id = args.quiz_id
        quiz_title = f"id={quiz_id}"
        current = "(unknown)"

    print(f"{action} : {quiz_title!r} (id={quiz_id})")
    if args.verbose and current != "(unknown)":
        print(f"Current : {current}")

    if args.dry_run:
        print(f"[DRY RUN] Would set published={target_state}")
        return

    try:
        result = update_quiz(base_url, token, args.course_id, quiz_id,
                             verbose=args.verbose, published=target_state)
    except Exception as e:
        print(f"[FAIL] {e}", file=sys.stderr)
        sys.exit(1)

    actual = result.get("published", "?")
    status = "published" if actual else "unpublished"
    print(f"[OK] Quiz {quiz_id} is now {status}")
    print(f"Quiz : {base_url}/courses/{args.course_id}/quizzes/{quiz_id}")


if __name__ == "__main__":
    main()
