#!/usr/bin/env python3
#
# Date: 2026-02-19
# Version: 1.2.0
# Purpose: HTTP helpers for Canvas API requests, including pagination and
#          multipart file upload (used for QTI/content migration imports).
# Usage: Imported by other modules.
# Input: Canvas base URL and token; endpoint URL.
# Output: Decoded JSON objects (Python dict/list).
# Chat name: Canvas SpeedGrader Archive
# AI Model: Claude Sonnet 4.6
# Attribution: Generated by Michael Gilchrist in collaboration with ChatGPT
#              and ClaudeAI Sonnet 4.6.

import json
import urllib.error
import urllib.request
import uuid


def http_get_json(url, token):
    req = urllib.request.Request(url)
    req.add_header("Authorization", f"Bearer {token}")
    req.add_header("Accept", "application/json")
    with urllib.request.urlopen(req) as resp:
        body = resp.read().decode("utf-8")
        return json.loads(body), resp.headers


def parse_next_link(headers):
    link = headers.get("Link")
    if not link:
        return None
    parts = [p.strip() for p in link.split(",")]
    for p in parts:
        if 'rel="next"' in p:
            lt = p.find("<")
            gt = p.find(">")
            if lt >= 0 and gt > lt:
                return p[lt + 1:gt]
    return None


def paginated_get_all_list_key(url, token, list_key, verbose=False):
    out = []
    cur = url
    while cur:
        if verbose:
            print(f"[GET] {cur}")
        data, headers = http_get_json(cur, token)

        if isinstance(data, dict) and list_key in data and isinstance(data[list_key], list):
            out.extend(data[list_key])
        elif isinstance(data, list):
            out.extend(data)
        else:
            out.append(data)

        cur = parse_next_link(headers)
    return out


def http_post_json(url, token, body):
    """POST JSON to a Canvas API endpoint with Bearer auth.
    Returns (parsed_json, headers).
    """
    payload = json.dumps(body).encode("utf-8")
    req = urllib.request.Request(url, data=payload, method="POST")
    req.add_header("Authorization", f"Bearer {token}")
    req.add_header("Content-Type", "application/json")
    req.add_header("Accept", "application/json")
    with urllib.request.urlopen(req) as resp:
        raw = resp.read().decode("utf-8")
        return json.loads(raw), resp.headers


def http_put_json(url, token, body):
    """PUT JSON to a Canvas API endpoint with Bearer auth.
    Returns (parsed_json, headers).
    """
    payload = json.dumps(body).encode("utf-8")
    req = urllib.request.Request(url, data=payload, method="PUT")
    req.add_header("Authorization", f"Bearer {token}")
    req.add_header("Content-Type", "application/json")
    req.add_header("Accept", "application/json")
    with urllib.request.urlopen(req) as resp:
        raw = resp.read().decode("utf-8")
        return json.loads(raw), resp.headers


def http_delete(url, token):
    """DELETE a Canvas resource with Bearer auth.
    Returns (parsed_json_or_None, headers).
    Canvas typically returns 200 with the deleted object, but may return
    204 (no content) on some endpoints.
    """
    req = urllib.request.Request(url, method="DELETE")
    req.add_header("Authorization", f"Bearer {token}")
    req.add_header("Accept", "application/json")
    try:
        with urllib.request.urlopen(req) as resp:
            raw = resp.read()
            if raw:
                return json.loads(raw.decode("utf-8")), resp.headers
            return None, resp.headers
    except urllib.error.HTTPError as e:
        if e.code == 204:
            return None, e.headers
        raise


def http_get_raw(url):
    """GET a URL without auth headers.  Returns raw bytes.
    Used for downloading files whose URL contains a verifier token
    (e.g. Canvas report CSV downloads where sending a Bearer header
    alongside the verifier causes authentication to fail).
    """
    req = urllib.request.Request(url)
    with urllib.request.urlopen(req) as resp:
        return resp.read()


def _build_multipart_body(boundary, fields, files):
    """Build a multipart/form-data body.

    fields: dict of str -> str  (plain form fields)
    files:  dict of field_name -> (filename, data_bytes, content_type)
    Returns: bytes
    """
    b = boundary.encode("ascii")
    parts = []
    for name, value in fields.items():
        parts.append(b"--" + b + b"\r\n")
        parts.append(
            f'Content-Disposition: form-data; name="{name}"\r\n\r\n'
            .encode("utf-8"))
        parts.append(str(value).encode("utf-8") + b"\r\n")
    for name, (filename, data, ctype) in files.items():
        parts.append(b"--" + b + b"\r\n")
        parts.append(
            (f'Content-Disposition: form-data; name="{name}"; '
             f'filename="{filename}"\r\n'
             f'Content-Type: {ctype}\r\n\r\n').encode("utf-8"))
        parts.append(data + b"\r\n")
    parts.append(b"--" + b + b"--\r\n")
    return b"".join(parts)


def http_post_multipart_no_auth(url, fields, files=None):
    """POST multipart/form-data WITHOUT a Bearer token.

    Used for the file upload step of Canvas's two-step upload flow
    (Step 2: POST to pre_attachment.upload_url).  The upload_url may be
    an S3 pre-signed endpoint (Authorization header would be rejected) or
    a Canvas internal endpoint (authorization embedded in upload_params).

    If the server returns 303 (S3 redirect to a Canvas confirm URL),
    this function follows it with a POST to complete the upload.

    fields: dict str -> str   (upload_params from the migration response)
    files:  dict of field_name -> (filename, data_bytes, content_type)
    Returns (response_body_bytes_or_None, headers).
    Raises urllib.error.HTTPError on unexpected errors.
    """
    boundary = uuid.uuid4().hex
    body = _build_multipart_body(boundary, fields, files or {})
    req = urllib.request.Request(url, data=body, method="POST")
    req.add_header("Content-Type",
                   f"multipart/form-data; boundary={boundary}")

    # Disable automatic redirect so we can handle 303 manually.
    class _NoRedirect(urllib.request.HTTPRedirectHandler):
        def redirect_request(self, req, fp, code, msg, headers, newurl):
            return None

    opener = urllib.request.build_opener(_NoRedirect)
    try:
        with opener.open(req) as resp:
            return resp.read(), resp.headers
    except urllib.error.HTTPError as e:
        if e.code == 303:
            # S3 -> Canvas confirm: POST to the redirect Location.
            loc = e.headers.get("Location")
            if loc:
                confirm = urllib.request.Request(
                    loc, data=b"", method="POST")
                confirm.add_header("Content-Length", "0")
                with urllib.request.urlopen(confirm) as resp:
                    return resp.read(), resp.headers
        if e.code in (201, 204):
            return None, e.headers
        raise


def paginated_get_all(url, token, verbose=False):
    out = []
    cur = url
    while cur:
        if verbose:
            print(f"[GET] {cur}")
        data, headers = http_get_json(cur, token)
        if isinstance(data, list):
            out.extend(data)
        else:
            out.append(data)
        cur = parse_next_link(headers)
    return out
