#!/usr/bin/env python3
#
# Date: 2026-02-20
# Version: 1.2.0
# Purpose: Small IO helpers for reading/writing JSON files, selecting inputs,
#          and loading the user profile (~/.canvas.api.conf).
# Usage: Imported by CLI scripts.
# Input: Paths.
# Output: Python objects or written files.
# Chat name: Canvas SpeedGrader Archive
# GPT Model: GPT-5.2 Thinking
# Attribution: Generated by Michael Gilchrist in collaboration with ChatGPT.

import configparser
import json
import os


def write_json(path, obj):
    os.makedirs(os.path.dirname(path), exist_ok=True)
    with open(path, "w", encoding="utf-8") as f:
        json.dump(obj, f, ensure_ascii=True, indent=2)


def read_json(path):
    with open(path, "r", encoding="utf-8") as f:
        return json.load(f)


def list_json_files(folder):
    out = []
    for name in sorted(os.listdir(folder)):
        if name.lower().endswith(".json"):
            out.append(os.path.join(folder, name))
    return out


_PROFILE_PATH = os.path.expanduser("~/.canvas.api.conf")


def load_profile(path=None):
    """Load the user profile from ~/.canvas.api.conf (INI format).

    Returns a dict of key/value pairs from the [default] section.
    Returns an empty dict if the file does not exist.
    Expands ~ in path-like values (token_file).
    """
    path = path or _PROFILE_PATH
    if not os.path.isfile(path):
        return {}
    cp = configparser.ConfigParser()
    cp.read(path, encoding="utf-8")
    if not cp.has_section("default"):
        return {}
    profile = dict(cp.items("default"))
    # Expand ~ in path-like keys
    for key in ("token_file",):
        if key in profile:
            profile[key] = os.path.expanduser(profile[key])
    return profile


def read_token(token, token_file, profile=None):
    """Return a Canvas API token.

    Fallback chain: --token > --token-file > profile token_file > error.
    """
    if token:
        return token.strip()
    if token_file:
        with open(token_file, "r", encoding="utf-8") as f:
            return f.read().strip()
    if profile and profile.get("token_file"):
        with open(profile["token_file"], "r", encoding="utf-8") as f:
            return f.read().strip()
    raise ValueError(
        "No token provided. Use --token, --token-file, "
        "or set token_file in ~/.canvas.api.conf."
    )
