#!/usr/bin/env python3
#
# Date: 2026-02-19
# Version: 1.1.0
# Purpose: Small IO helpers for reading/writing JSON files and selecting inputs.
# Usage: Imported by CLI scripts.
# Input: Paths.
# Output: Python objects or written files.
# Chat name: Canvas SpeedGrader Archive
# GPT Model: GPT-5.2 Thinking
# Attribution: Generated by Michael Gilchrist in collaboration with ChatGPT.

import json
import os


def write_json(path, obj):
    os.makedirs(os.path.dirname(path), exist_ok=True)
    with open(path, "w", encoding="utf-8") as f:
        json.dump(obj, f, ensure_ascii=True, indent=2)


def read_json(path):
    with open(path, "r", encoding="utf-8") as f:
        return json.load(f)


def list_json_files(folder):
    out = []
    for name in sorted(os.listdir(folder)):
        if name.lower().endswith(".json"):
            out.append(os.path.join(folder, name))
    return out


def read_token(token, token_file):
    """Return a Canvas API token from an inline string or a file path.
    Raises ValueError if neither source is provided.
    """
    if token:
        return token.strip()
    if token_file:
        with open(token_file, "r", encoding="utf-8") as f:
            return f.read().strip()
    raise ValueError("No token provided. Use --token or --token-file.")
