#!/usr/bin/env python3
# ============================================================================
# Script:       list_quizzes.py
# Version:      1.0.0
# Date:         2026-02-19
# Purpose:      List all quizzes in a Canvas course with ID, title, type,
#               published status, due date, and submission count.
#
# Usage:        list_quizzes.py COURSE_ID --base-url URL
#                   [--token TOKEN | --token-file FILE]
#                   [--published-only] [--verbose] [--help]
#
# Input:        Canvas API token + course_id
# Output:       Tabular quiz listing to stdout
#
# Options:
#   --base-url URL          Canvas instance URL (required)
#   --token TOKEN           Inline API token
#   --token-file FILE       Path to file containing API token
#   --published-only        Only show published quizzes
#   -v, --verbose           Show detailed output
#   -h, --help              Show this help message
#
# Session:      Canvas Quiz Database Creation
# AI Model:     Claude Opus 4.6
# Attribution:  Generated by Michael Gilchrist in collaboration with
#               ClaudeAI Opus 4.6
# ============================================================================

import argparse

from canvas_api import get_quizzes
from io_utils import read_token


def main():
    ap = argparse.ArgumentParser(
        description="List all quizzes in a Canvas course.")
    ap.add_argument("course_id", type=int,
                    help="Canvas course ID")

    ap.add_argument("--base-url", required=True,
                    help="Canvas instance URL "
                         "(e.g. https://utk.instructure.com)")
    ap.add_argument("--token", default=None,
                    help="Canvas API token (inline)")
    ap.add_argument("--token-file", default=None,
                    help="Path to file containing Canvas API token")

    ap.add_argument("--published-only", action="store_true",
                    help="Only show published quizzes")
    ap.add_argument("-v", "--verbose", action="store_true",
                    help="Show detailed output")

    args = ap.parse_args()

    token = read_token(args.token, args.token_file)
    base_url = args.base_url.rstrip("/")

    if args.verbose:
        print(f"[INFO] Fetching quizzes for course {args.course_id}...")

    quizzes = get_quizzes(base_url, token, args.course_id,
                          verbose=args.verbose)

    if args.published_only:
        quizzes = [q for q in quizzes if q.get("published")]

    # Sort by title for readability
    quizzes.sort(key=lambda q: q.get("title", ""))

    if not quizzes:
        print("No quizzes found.")
        return

    # Print table header
    print(f"{'ID':>8}  {'Pts':>6}  {'Subs':>5}  {'Published':>9}  "
          f"{'Quiz Type':<20}  Title")
    print(f"{'---':>8}  {'---':>6}  {'---':>5}  {'---':>9}  "
          f"{'---':<20}  ---")

    for q in quizzes:
        qid = q.get("id", "")
        title = q.get("title", "(untitled)")
        quiz_type = q.get("quiz_type", "")
        published = "yes" if q.get("published") else "no"
        points = q.get("points_possible")
        pts_str = f"{points:g}" if points is not None else "-"
        # submission_count may not be present for unpublished quizzes
        subs = q.get("submission_count", "")
        sub_str = str(subs) if subs != "" else "-"

        print(f"{qid:>8}  {pts_str:>6}  {sub_str:>5}  {published:>9}  "
              f"{quiz_type:<20}  {title}")

    print(f"\nTotal: {len(quizzes)} quizzes")


if __name__ == "__main__":
    main()
