#!/usr/bin/env python3
#
# Date: 2026-01-25
# Version: 1.0.0
# Purpose: Write canonical per-submission JSON dict(s) to SQLite.
# Usage: Imported by json_to_sqlite.py (and json_to_all.py).
# Input: One or more canonical per-submission dicts.
# Output: SQLite database with submissions and question_records tables.
# Chat name: Canvas SpeedGrader Archive
# GPT Model: GPT-5.2 Thinking
# Attribution: Generated by Michael Gilchrist in collaboration with ChatGPT.

import json
import sqlite3


def init_db(db_path):
    conn = sqlite3.connect(db_path)
    cur = conn.cursor()

    cur.execute(
        '''
        CREATE TABLE IF NOT EXISTS submissions (
            submission_id INTEGER PRIMARY KEY,
            student_id INTEGER,
            quiz_id INTEGER,
            quiz_name TEXT,
            time_start TEXT,
            time_end TEXT,
            time_total INTEGER,
            points_total REAL
        )
        '''
    )

    cur.execute(
        '''
        CREATE TABLE IF NOT EXISTS question_records (
            submission_id INTEGER NOT NULL,
            student_id INTEGER,
            quiz_id INTEGER,

            question_id INTEGER NOT NULL,
            question_position INTEGER,
            question_type TEXT,

            question_prompt_html TEXT,
            question_response_obj_json TEXT,
            question_response_html TEXT,
            question_key_html TEXT,

            points_possible REAL,
            earned_points REAL,

            PRIMARY KEY (submission_id, question_id)
        )
        '''
    )

    conn.commit()
    return conn


def upsert_submission(conn, header):
    cur = conn.cursor()
    cur.execute(
        '''
        INSERT OR REPLACE INTO submissions (
            submission_id, student_id, quiz_id, quiz_name,
            time_start, time_end, time_total, points_total
        ) VALUES (?, ?, ?, ?, ?, ?, ?, ?)
        ''',
        (
            header.get("submission_id"),
            header.get("student_id"),
            header.get("quiz_id"),
            header.get("quiz_name"),
            header.get("time_start"),
            header.get("time_end"),
            header.get("time_total"),
            header.get("points_total"),
        )
    )
    conn.commit()


def upsert_question(conn, q):
    cur = conn.cursor()
    cur.execute(
        '''
        INSERT OR REPLACE INTO question_records (
            submission_id, student_id, quiz_id,
            question_id, question_position, question_type,
            question_prompt_html, question_response_obj_json, question_response_html, question_key_html,
            points_possible, earned_points
        ) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
        ''',
        (
            q.get("submission_id"),
            q.get("student_id"),
            q.get("quiz_id"),
            q.get("question_id"),
            q.get("question_position"),
            q.get("question_type"),
            q.get("question_prompt_html"),
            json.dumps(q.get("question_response_obj"), ensure_ascii=True),
            q.get("question_response_html"),
            q.get("question_key_html"),
            q.get("points_possible"),
            q.get("earned_points"),
        )
    )
    conn.commit()


def write_doc(conn, doc):
    header = (doc.get("submission") or {})
    upsert_submission(conn, header)
    for q in (doc.get("questions") or []):
        upsert_question(conn, q)
